### ISSUE TITLE
Please add syntax highlighting for Sublime Text

### ISSUE THREAD

**Issue by ghost** [fusionlanguage/fut#89]

**Comment by Ivorforce** [comment]
I recommend to supply a `.tmLanguage` file. Most code editors support those, and it's way easier than other ways to get basic syntax highlighting into a language.
The format takes a bit of getting used to, especially when you come straight out of EBNF like notation, but it's not too bad. I made mine in an evening or two (feel free to [use it as reference](https://github.com/Ivorforce/Monoteny/blob/main/resources/Monoteny.tmbundle/Syntaxes/monoteny.tmLanguage)).

**Comment by pfusik** [comment]
A `.tmLanguage` could probably be converted from [.tmLanguage.json](https://github.com/fusionlanguage/fut/blob/master/editors/vscode/syntaxes/fusion.tmLanguage.json) ?

**Comment by Ivorforce** [comment]
Oh, yeah that's basically the same format. With some luck perhaps sublime can even load the json, otherwise i believe I've seen conversion tools too.

**Comment by nlapinski** [comment]
Should be able to save as a `Fusion.sublime-syntax` in ~\Sublime Text 3\Packages\User\Fut

Its not perfect, but it handles some of the syntax, $ and # usage need to be added, and string escape is not fully handled. I'll put in a pull request at some point but here is the yaml if some one would like it.

![image](https://github.com/user-attachments/assets/4d8b1c52-9cf8-4484-9361-7900202b9d40)


```
%YAML 1.2
---
# http://www.sublimetext.com/docs/syntax.html
name: Fusion
file_extensions:
  - fu
scope: source.fu

contexts:
  main:
    - include: numbers
    - include: preprocessor
    - include: comment
    - include: storage-modifier
    - include: enum-declaration
    - include: native-statement
    - include: type
    - include: method-declaration
    - include: class-declaration

  type-template:
    - match: '\b(List|HashSet|Queue|Stack|SortedSet|Dictionary|SortedDictionary|OrderedDictionary)\s*(<)'
      captures:
        1: entity.name.type.fu  # The type (e.g., List or HashSet)
        2: entity.generic.type.fu  # The opening '<' gets the same scope as the type
      push:
        - meta_scope: meta.generic.type.fu
        - match: '>'
          captures:
            0: entity.generic.type.fu  # The closing '>' gets the same scope as the type
          pop: true
        - include: type-in-template

  type-in-template:
    - match: '\b([A-Za-z_][A-Za-z0-9_]*|int|float|double|char|bool|string)\b'
      captures:
        0: storage.type.type.fu  # Highlighting the type inside the template

  keywords:
    - match: '\b(if|else|while|for|foreach|return|continue|break|switch|case|default|try|catch|finally|throw)\b'
      scope: keyword.control.fu
    - match: '\b(public|private|protected|internal|static|virtual|override|abstract|const)\b'
      scope: storage.modifier.fu
    - match: '\b(void|int|float|double|char|bool|string)\b'
      scope: storage.type.fu
    - match: '\b(true|false|null)\b'
      scope: constant.language.fu

  numbers:
    # Decimal floating-point numbers
    - match: '\b\d+(\.\d+)?([eE][-+]?\d+)?[fFdD]?\b'
      scope: constant.numeric.float.fu
    # Hexadecimal numbers
    - match: '\b0x[0-9a-fA-F]+\b'
      scope: constant.numeric.hexadecimal.fu
    # Binary numbers
    - match: '\b0b[01]+\b'
      scope: constant.numeric.binary.fu
    # Decimal integer numbers
    - match: '\b\d+\b'
      scope: constant.numeric.decimal.fu

  comment:
    - match: /\*
      captures:
        0: punctuation.definition.comment.fu
      push:
        - meta_scope: comment.block.fu
        - match: \*/
          captures:
            0: punctuation.definition.comment.fu
          pop: true
    - match: (^\s+)?(?=//)
      captures:
        1: punctuation.whitespace.comment.leading.fu
      push:
        - match: (?=$)
          pop: true
        - match: (?<!/)///(?!/)
          captures:
            0: punctuation.definition.comment.fu
          push:
            - meta_scope: comment.block.documentation.fu
            - match: (?=$)
              pop: true
        - match: (?<!/)//(?:(?!/)|(?=//))
          captures:
            0: punctuation.definition.comment.fu
          push:
            - meta_scope: comment.line.double-slash.fu
            - match: (?=$)
              pop: true
  aggregate-initializer:
    - match: '\{'
      captures:
        0: punctuation.curlybrace.open.fu
      push:
        - match: '\}'
          captures:
            0: punctuation.curlybrace.close.fu
          pop: true
        - include: expression
        - include: punctuation-comma
  assert-statement:
    - match: \bassert\b
      captures:
        0: keyword.control.assert.fu
      push:
        - match: (?=;)
          pop: true
        - include: expression
        - include: punctuation-comma
  base-expression:
    - match: \bbase\b
      captures:
        0: keyword.other.base.fu
  block:
    - match: '\{'
      captures:
        0: punctuation.curlybrace.open.fu
      push:
        - match: '\}'
          captures:
            0: punctuation.curlybrace.close.fu
          pop: true
        - include: statement
  boolean-literal:
    - match: \btrue\b
      scope: constant.language.boolean.true.fu
    - match: \bfalse\b
      scope: constant.language.boolean.false.fu
  break-statement:
    - match: \bbreak\b
      captures:
        0: keyword.control.flow.break.fu
  char-character-escape:
    - match: '\\([''"\\0abfnrtv])'
      scope: constant.character.escape.fu
  char-literal:
    - match: "'"
      captures:
        0: punctuation.definition.char.begin.fu
      push:
        - meta_scope: string.quoted.single.fu
        - match: '('')|((?:[^\\\n])$)'
          captures:
            1: punctuation.definition.char.end.fu
            2: invalid.illegal.newline.fu
          pop: true
        - include: char-character-escape

  class-builtin:
    - match: \b(Console|Convert|Dictionary|Encoding|Environment|Exception|HashSet|JsonElement|List|Lock|Match|Math|Regex|RegexOptions|SortedDictionary|SortedSet|Stack|StringWriter|TextWriter)\b
      captures:
        1: support.class.fu
  class-declaration:
    - match: (?=\b(?:static|abstract|sealed|class)\b)
      push:
        - match: '(?<=\})'
          pop: true
        - match: '\b(?:(static|abstract|sealed)\s+)?(class)\s+([A-Z][0-9A-Za-z_]*)\s*(?:(:)\s*[A-Z][0-9A-Za-z_]*)?'
          captures:
            1: storage.modifier.fu
            2: storage.type.class.fu
            3: entity.name.type.class.fu
            4: punctuation.separator.colon.fu
          push:
            - match: '(?=\{)'
              pop: true
            - include: preprocessor
            - include: comment
        - match: '\{'
          captures:
            0: punctuation.curlybrace.open.fu
          push:
            - match: '\}'
              captures:
                0: punctuation.curlybrace.close.fu
              pop: true
            - include: preprocessor
            - include: comment
            - include: storage-modifier
            - include: type
            - include: field
            - include: initializer
            - include: method-declaration
        - include: preprocessor
        - include: comment
  continue-statement:
    - match: \bcontinue\b
      captures:
        0: keyword.control.flow.continue.fu
  do-statement:
    - match: \bdo\b
      captures:
        0: keyword.control.loop.do.fu
      push:
        - match: '(?=;|})'
          pop: true
        - include: statement
  else-statement:
    - match: \belse\b
      captures:
        0: keyword.control.conditional.else.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - include: statement
  enum-declaration:
    - match: (?=\benum\b)
      push:
        - match: '(?<=\})'
          pop: true
        - match: (?=enum)
          push:
            - match: '(?=\{)'
              pop: true
            - include: preprocessor
            - include: comment
            - match: '(enum)\s*\*?\s+([A-Z][0-9A-Za-z_]*)'
              captures:
                1: keyword.other.enum.fu
                2: entity.name.type.enum.fu
        - match: '\{'
          captures:
            0: punctuation.curlybrace.open.fu
          push:
            - match: '\}'
              captures:
                0: punctuation.curlybrace.close.fu
              pop: true
            - include: preprocessor
            - include: comment
            - include: punctuation-comma
            - match: '[A-Z][0-9A-Za-z_]*'
              captures:
                0: entity.name.variable.enum-member.fu
              push:
                - match: '(?=(,|\}))'
                  pop: true
                - include: preprocessor
                - include: comment
                - include: initializer
        - include: preprocessor
        - include: comment
  expression:
    - include: preprocessor
    - include: comment
    - include: new-expression
    - include: resource-expression
    - include: expression-operators
    - include: base-expression
    - include: this-expression
    - include: literal

  expression-body:
    - match: '=>'
      captures:
        0: keyword.operator.arrow.fu
      push:
        - match: (?=;)
          pop: true
        - include: expression
  expression-operators:
    - match: '[-+*/%]='
      scope: keyword.operator.assignment.compound.fu
    - match: '[&|^]=|<<=|>>='
      scope: keyword.operator.assignment.compound.bitwise.fu
    - match: '<<|>>'
      scope: keyword.operator.bitwise.shift.fu
    - match: '==|!='
      scope: keyword.operator.comparison.fu
    - match: <=|>=|<|>
      scope: keyword.operator.relational.fu
    - match: \!|&&|\|\|
      scope: keyword.operator.logical.fu
    - match: ~|\&|\||\^
      scope: keyword.operator.bitwise.fu
    - match: \=
      scope: keyword.operator.assignment.fu
    - match: '--'
      scope: keyword.operator.decrement.fu
    - match: \+\+
      scope: keyword.operator.increment.fu
    - match: '[-+*/%]'
      scope: keyword.operator.arithmetic.fu
    - match: \bis\b
      scope: keyword.operator.expression.pattern.is.fu
  field:
    - match: '([A-Z][0-9A-Za-z_]*)(?=\s*[=;])'
      captures:
        0: entity.name.variable.field.fu
  for-statement:
    - match: \b(for)\s*(?=\()
      captures:
        1: keyword.control.loop.for.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: expression
            - include: type
            - include: punctuation-semicolon
        - include: statement
  foreach-statement:
    - match: \b(foreach)\s*(?=\()
      captures:
        1: keyword.control.loop.foreach.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: type
            - match: \bin\b
              scope: keyword.control.loop.in.fu
            - include: expression
        - include: statement
  if-statement:
    - match: \b(if)\s*(?=\()
      captures:
        1: keyword.control.conditional.if.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: expression
        - include: statement
  initializer:
    - match: (?<!=|!)=(?!=|>)
      captures:
        0: keyword.operator.assignment.fu
      push:
        - match: '(?=[,);}])'
          pop: true
        - include: expression
        - include: aggregate-initializer
  literal:
    - include: boolean-literal
    - include: null-literal
    - include: char-literal
    - include: string-literal
    - include: numbers

  local-constant-declaration:
    - match: \bconst\b
      captures:
        0: storage.modifier.fu
      push:
        - match: (?=;)
          pop: true
        - match: '@?[_[:alpha:]][_[:alnum:]]*'
          scope: entity.name.variable.local.fu
        - include: preprocessor
        - include: comment
        - include: type
        - include: initializer
  lock-statement:
    - match: \b(lock)\s*(?=\()
      captures:
        1: keyword.other.lock.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: expression
        - include: statement
  method-declaration:
    - match: '([A-Z][0-9A-Za-z_]*)!?(?=\()'
      captures:
        1: entity.name.function.fu
      push:
        - match: '(?<=\})|;'
          pop: true
        - include: preprocessor
        - include: comment
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: preprocessor
            - include: comment
            - include: type
            - include: parameter
            - include: initializer
            - include: punctuation-comma
        - match: \bthrows\b
          captures:
            0: keyword.other.throws.fu
          push:
            - match: '(?=[{;])'
              pop: true
            - include: preprocessor
            - include: comment
            - match: '[A-Z][0-9A-Za-z_]*'
              scope: entity.name.type.class.fu
            - include: punctuation-comma
        - include: expression-body
        - include: block
  native-block:
    - match: '\{'
      captures:
        0: punctuation.curlybrace.open.fu
      push:
        - match: '\}'
          captures:
            0: punctuation.curlybrace.close.fu
          pop: true
        - include: comment
        - include: literal
        - include: native-block
  native-statement:
    - match: \bnative\b
      captures:
        0: keyword.other.native.fu
      push:
        - match: '(?<=\})'
          pop: true
        - include: preprocessor
        - include: comment
        - include: native-block
  new-expression:
    - match: \bnew\b
      captures:
        0: keyword.other.new.fu
      push:
        - match: '(?=[;,)])'
          pop: true
        - include: preprocessor
        - include: comment
        - include: type
        - include: aggregate-initializer
  null-literal:
    - match: \bnull\b
      scope: constant.language.null.fu
  parameter:
    - match: '([a-z][0-9A-Za-z_]*)(?=\s*[=,)])'
      captures:
        0: entity.name.variable.parameter.fu
  preprocessor:
    - match: ^\s*(#)\s*
      captures:
        1: punctuation.separator.hash.fu
      push:
        - meta_scope: meta.preprocessor.fu
        - match: (?<=$)
          pop: true
        - include: comment
        - include: preprocessor-if-or-elif
        - include: preprocessor-else
        - include: preprocessor-endif
  preprocessor-else:
    - match: \belse\b
      captures:
        0: keyword.preprocessor.else.fu
  preprocessor-endif:
    - match: \bendif\b
      captures:
        0: keyword.preprocessor.endif.fu
  preprocessor-expression:
    - match: \(
      captures:
        0: punctuation.parenthesis.open.fu
      push:
        - match: \)
          captures:
            0: punctuation.parenthesis.close.fu
          pop: true
        - include: preprocessor-expression
    - match: '\b(?:(true)|(false)|([A-Za-z_][0-9A-Za-z_]*))\b'
      captures:
        1: constant.language.boolean.true.fu
        2: constant.language.boolean.false.fu
        3: entity.name.variable.preprocessor.symbol.fu
    - match: '!|&&|\|\|'
      captures:
        0: keyword.operator.logical.fu
    - match: '[=!]='
      captures:
        0: keyword.operator.comparison.fu
  preprocessor-if-or-elif:
    - match: \b(?:(if)|(elif))\b
      captures:
        1: keyword.preprocessor.if.fu
        2: keyword.preprocessor.elif.fu
      push:
        - match: (?=$)
          pop: true
        - include: comment
        - include: preprocessor-expression
  punctuation-comma:
    - match: ','
      scope: punctuation.separator.comma.fu
  punctuation-semicolon:
    - match: ;
      scope: punctuation.terminator.statement.fu
  resource-expression:
    - match: '\b(resource)\s*(<)\s*(byte)\s*(\[)\s*(\])\s*(>)\s*(\()'
      captures:
        1: keyword.other.resource.fu
        2: punctuation.definition.typeparameters.begin.fu
        3: keyword.type.fu
        4: punctuation.squarebracket.open.fu
        5: punctuation.squarebracket.close.fu
        6: punctuation.definition.typeparameters.end.fu
        7: punctuation.parenthesis.open.fu
      push:
        - match: \)
          captures:
            1: punctuation.parenthesis.close.fu
          pop: true
        - include: expression
  return-statement:
    - match: \breturn\b
      captures:
        0: keyword.control.flow.return.fu
      push:
        - match: (?=;)
          pop: true
        - include: expression
  statement:
    - include: assert-statement
    - include: break-statement
    - include: continue-statement
    - include: do-statement
    - include: for-statement
    - include: foreach-statement
    - include: if-statement
    - include: else-statement
    - include: lock-statement
    - include: native-statement
    - include: return-statement
    - include: switch-statement
    - include: throw-statement
    - include: while-statement
    - include: block
    - include: local-constant-declaration
    - include: type
    - include: initializer
    - include: expression
    - include: punctuation-semicolon
  # storage-modifier-access:
  #   - match: \b(internal|protected|public|static|abstract|virtual|override|sealed|const)\b
  #     scope: storage.modifier.fu
  storage-modifier:
    - match: \b(internal|protected|public|static|abstract|virtual|override|sealed|const)\b
      scope: storage.modifier.fu
  string-literal:
    - match: '"'
      captures:
        0: punctuation.definition.string.begin.fu
      push:
        - meta_scope: string.quoted.double.fu
        - match: '(")|((?:[^\\\n])$)'
          captures:
            1: punctuation.definition.string.end.fu
            2: invalid.illegal.newline.fu
          pop: true
        - include: char-character-escape
  switch-label:
    - match: \b(case)\s+
      captures:
        1: keyword.control.case.fu
      push:
        - match: ':'
          captures:
            0: punctuation.separator.colon.fu
          pop: true
        - include: expression
        - include: switch-when-clause
    - match: \b(default)\s*(:)
      captures:
        1: keyword.control.default.fu
        2: punctuation.separator.colon.fu
  switch-statement:
    - match: \b(switch)\s*(?=\()
      captures:
        1: keyword.control.switch.fu
      push:
        - match: '(?<=\})'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: expression
        - match: '\{'
          captures:
            0: punctuation.curlybrace.open.fu
          push:
            - match: '\}'
              captures:
                0: punctuation.curlybrace.close.fu
              pop: true
            - include: switch-label
            - include: statement
  switch-when-clause:
    - match: \bwhen\b
      captures:
        0: keyword.control.when.fu
  this-expression:
    - match: \bthis\b
      captures:
        0: keyword.other.this.fu
  throw-statement:
    - match: '\b(throw)\s+([A-Z][0-9A-Za-z_]*)\s*(\()'
      captures:
        1: keyword.control.flow.throw.fu
        2: entity.name.type.class.fu
        3: punctuation.parenthesis.open.fu
      push:
        - match: \)?(?=;)
          captures:
            0: punctuation.parenthesis.close.fu
          pop: true
        - include: expression
  type:
    - include: preprocessor
    - include: comment
    - include: method-accessor
    - include: type-template
    - include: type-builtin
    - include: class-builtin
    - include: type-storage-suffix
    - include: type-array-suffix

  type-arguments:
    - match: <
      captures:
        0: punctuation.definition.typeparameters.begin.fu
      push:
        - match: '>'
          captures:
            0: punctuation.definition.typeparameters.end.fu
          pop: true
        - include: preprocessor
        - include: comment
        - include: type
        - include: punctuation-comma
  type-array-suffix:
    - match: '\['
      captures:
        0: punctuation.squarebracket.open.fu
      push:
        - match: '(\])\s*([!#])?'
          captures:
            1: punctuation.squarebracket.close.fu
          pop: true
        - include: expression
  type-builtin:
    - match: \b(bool|byte|double|float|int|long|nint|sbyte|short|string|uint|ulong|ushort|void)\b
      captures:
        1: storage.type.fu
        #1: keyword.type.fu
  type-storage-suffix:
    - match: (\()\s*(\))
      captures:
        1: punctuation.parenthesis.open.fu
        2: punctuation.parenthesis.close.fu
  while-statement:
    - match: \b(while)\s*(?=\()
      captures:
        1: keyword.control.loop.while.fu
      push:
        - match: '(?<=\})|(?=;)'
          pop: true
        - match: \(
          captures:
            0: punctuation.parenthesis.open.fu
          push:
            - match: \)
              captures:
                0: punctuation.parenthesis.close.fu
              pop: true
            - include: expression
        - include: statement

  method-accessor:
    - match: '\b([A-Za-z_][A-Za-z0-9_]*)\s*(\.\s*[A-Za-z_][A-Za-z0-9_]*)\s*(\()'
      captures:
        1: variable.annotation.fu
        2: entity.name.function.fu
        #2: storage.type.fu
        3: punctuation.definition.parameters.fu
      push:
        - meta_scope: meta.method-call.fu
        - match: '\)'
          captures:
            0: punctuation.definition.parameters.fu
          pop: true
        - include: expression
        - include: punctuation-comma

```
